# Generated by Django 3.2.6 on 2021-08-31 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the target')),
                ('description', models.CharField(max_length=200, verbose_name='Brief')),
                ('workflow', models.CharField(choices=[('assigned', 'Assigned'), ('failed', 'Failed'), ('completed', 'Completed')], default='active', max_length=10, verbose_name='State Workflow')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits_created', to=settings.AUTH_USER_MODEL)),
                ('hitman', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
