# Generated by Django 3.2.6 on 2021-09-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitmanprofile',
            old_name='managers',
            new_name='manages',
        ),
    ]
