# Generated by Django 3.2.6 on 2021-09-02 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_rename_managers_hitmanprofile_manages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitmanprofile',
            name='manages',
            field=models.ManyToManyField(blank=True, related_name='hitman_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
